spring:
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: http://example.org
          predicates:
            - Path=/example/**
        - id: load_balanced_route
          uri: lb://example-service
          predicates:
            - Path=/loadbalanced/**
        - id: resilience_route
          uri: https://httpbin.org/get
          predicates:
            - Path=/resilience/**
          filters:
            - name: CircuitBreaker
              args:
                name: exampleCircuitBreaker

resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
