server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8085
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /customers/$\{segment}
            - name: CustomRateLimiter
            - name: CustomCache
        - id: billing_route
          uri: http://localhost:8086
          predicates:
            - Path=/api/billing/**
          filters:
            - RewritePath=/api/billing/(?<segment>.*), /billing/$\{segment}
            - name: CustomRateLimiter
